[package]
name = "ferrous-beats"
version = "0.1.0"
edition = "2021"
authors = ["Janusz Piechówka"]
repository = "https://github.com/jpiechowka/ferrous-beats"
license = "MIT OR Apache-2.0"
description = "Rust music player"
readme = "README.md"

[profile.release]
opt-level = 3
codegen-units = 1
panic = "abort"
lto = true
strip = true

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
tokio = { version = "1.39.2", features = ["full"] }
tower = "0.5.0"
tower-http = { version = "0.5.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
